In [1]:
import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt

In [2]:
train = pd.read_csv("titanic/train.csv", skipinitialspace=True)
test = pd.read_csv("titanic/test.csv", skipinitialspace=True)

In [3]:
train.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [4]:
print(train.describe())
train.shape

       PassengerId    Survived      Pclass         Age       SibSp  \
count   891.000000  891.000000  891.000000  714.000000  891.000000   
mean    446.000000    0.383838    2.308642   29.699118    0.523008   
std     257.353842    0.486592    0.836071   14.526497    1.102743   
min       1.000000    0.000000    1.000000    0.420000    0.000000   
25%     223.500000    0.000000    2.000000   20.125000    0.000000   
50%     446.000000    0.000000    3.000000   28.000000    0.000000   
75%     668.500000    1.000000    3.000000   38.000000    1.000000   
max     891.000000    1.000000    3.000000   80.000000    8.000000   

            Parch        Fare  
count  891.000000  891.000000  
mean     0.381594   32.204208  
std      0.806057   49.693429  
min      0.000000    0.000000  
25%      0.000000    7.910400  
50%      0.000000   14.454200  
75%      0.000000   31.000000  
max      6.000000  512.329200  


(891, 12)

In [5]:
train.isna().sum()


PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [6]:
train["Sex"][train["Sex"]=="female"] = 1
train["Sex"][train["Sex"]=="male"]=0
test["Sex"][test["Sex"]=="female"] = 1
test["Sex"][test["Sex"]=="male"]=0

/home/islam/.conda/envs/py36/lib/python3.6/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.
/home/islam/.conda/envs/py36/lib/python3.6/site-packages/ipykernel_launcher.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  
/home/islam/.conda/envs/py36/lib/python3.6/site-packages/ipykernel_launcher.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  This is separate from the ipykernel package so we can avo

In [7]:
train.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name Sex   Age  SibSp  Parch  \
0                            Braund, Mr. Owen Harris   0  22.0      1      0   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...   1  38.0      1      0   
2                             Heikkinen, Miss. Laina   1  26.0      0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)   1  35.0      1      0   
4                           Allen, Mr. William Henry   0  35.0      0      0   

             Ticket     Fare Cabin Embarked  
0         A/5 21171   7.2500   NaN        S  
1          PC 17599  71.2833   C85        C  
2  STON/O2. 3101282   7.9250   NaN        S  
3            113803  53.1000  C123        S  
4            373450   8.0500   NaN        S

In [31]:

train.fillna(train['Age'].dropna().median(), inplace = True)
train["Embarked"].fillna("S", inplace=True)


In [9]:
test.fillna(test['Age'].dropna().median(), inplace = True)
test["Embarked"].fillna("S", inplace=True)

In [10]:
embarked_mapping = {"S": 0, "C": 1, "Q": 2}
train['Embarked'] = train["Embarked"].map(embarked_mapping)
test['Embarked'] = test["Embarked"].map(embarked_mapping)

In [32]:
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

val = train[["Pclass", "Sex", "Age", "Fare", "SibSp", "Parch", "Embarked"]]
val.fillna(val.dropna().median(), inplace = True)

X = val[["Pclass", "Sex", "Age", "Fare", "SibSp", "Parch", "Embarked"]].values
y = train['Survived'].values


scaler = StandardScaler()

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=.4, random_state=42)

X_train = scaler.fit_transform( X_train )
X_test = scaler.transform( X_test )



/home/islam/.conda/envs/py36/lib/python3.6/site-packages/pandas/core/generic.py:5434: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self._update_inplace(new_data)


In [33]:
from sklearn.tree import DecisionTreeClassifier

model_one = DecisionTreeClassifier()
model_one.fit(X_train, y_train)

print(model_one.feature_importances_)
print("Score on training set = %f" % (model_one.score(X_train, y_train)))
print("Score on test set = %f" % (model_one.score(X_test, y_test)))

[0.10346486 0.32736511 0.26815972 0.21567944 0.02617797 0.02888772
 0.03026519]
Score on training set = 0.983146
Score on test set = 0.736695


In [34]:
from sklearn.model_selection import cross_val_score
f = DecisionTreeClassifier(max_depth=5)
print(cross_val_score(f, X, y, cv=3))

[0.78787879 0.81818182 0.8013468 ]


In [35]:
from sklearn.ensemble import RandomForestClassifier
print(cross_val_score(RandomForestClassifier(n_estimators=100, max_depth=5), X, y, cv=3))

[0.79461279 0.82491582 0.82491582]


In [90]:
from sklearn.svm import SVC
print(cross_val_score( SVC(kernel="linear", C=0.25), X, y, cv=3))

[0.79124579 0.8013468  0.77104377]


In [101]:
print(cross_val_score( SVC(gamma=0.004, C=1), X, y, cv=3))

[0.65993266 0.72053872 0.73400673]


In [57]:
from sklearn.neural_network import MLPClassifier
print(cross_val_score( MLPClassifier(hidden_layer_sizes=(1000, ),alpha=0.01, max_iter=1000), X, y, cv=3))

[0.78451178 0.78787879 0.80808081]


In [58]:
from sklearn.neighbors import KNeighborsClassifier
print(cross_val_score( KNeighborsClassifier(3), X, y, cv=3))

[0.65656566 0.71043771 0.68686869]


In [59]:
from sklearn.naive_bayes import GaussianNB
print(cross_val_score( GaussianNB(), X, y, cv=3))

[0.77441077 0.75757576 0.78114478]


In [75]:
model_two = RandomForestClassifier(n_estimators=100, max_depth=7)
model_two.fit(X_train, y_train)

print(model_two.feature_importances_)
print("Score on training set = %f" % (model_two.score(X_train, y_train)))
print("Score on test set = %f" % (model_two.score(X_test, y_test)))

[0.11927087 0.39353274 0.16111336 0.18629691 0.05024104 0.0439867
 0.04555837]
Score on training set = 0.898876
Score on test set = 0.823529


In [85]:
test['Survived_DecisionTree'] = model_one.predict(test[["Pclass", "Sex", "Age", "Fare", "SibSp", "Parch", "Embarked"]].values)
test['Survived_RandomForest'] = model_two.predict(test[["Pclass", "Sex", "Age", "Fare", "SibSp", "Parch", "Embarked"]].values)

In [108]:
from sklearn.linear_model import LogisticRegression
model_three = LogisticRegression()
model_three.fit(X_train, y_train)

print(model_three.coef_)
print("Score on training set = %f" % (model_three.score(X_train, y_train)))
print("Score on test set = %f" % (model_three.score(X_test, y_test)))

[[-0.77556727  1.27956535 -0.40004736  0.14047288 -0.34667442 -0.0791167
   0.21516543]]
Score on training set = 0.803371
Score on test set = 0.792717


/home/islam/.conda/envs/py36/lib/python3.6/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


In [109]:
test['Survived_LogisticRegression'] = model_one.predict(test[["Pclass", "Sex", "Age", "Fare", "SibSp", "Parch", "Embarked"]].values)

In [112]:
test.to_csv("Output_Predict_test.csv")